version: "3.7"
services:
  database:
    container_name: "pgdb"
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - data:/var/lib/postgresql/data/
  server_postgres:
    container_name: "serverpg"
    build:
      context: .
    environment:
      - ENABLE_DB=true
    ports:
      - "8085:8085"
    restart: unless-stopped
    depends_on:
      - database
    tty: true
    volumes:
      - ./log.txt:/build/log.txt
  server_cache:
    container_name: "server_cache"
    build:
      context: .
    environment:
        - ENABLE_DB=false
    ports:
      - "8085:8085"
    restart: unless-stopped
    tty: true
    volumes:
      - .:.
volumes:
  data:
