version: "3.7"
services:
  database:
    container_name: "pgdb"
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGDATA=/tmp
    volumes:
      - data:/var/lib/postgresql/data/
  server:
    container_name: "myserver"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=database
    ports:
#      - "8080:8080"
      - "8085:8085"
    restart: unless-stopped
    tty: true
    depends_on:
      - database
volumes:
  data: